#ifndef GEOGRAM_BASIC_VERSION
#define GEOGRAM_BASIC_VERSION

#define VORPALINE_VERSION_MAJOR "1"
#define VORPALINE_VERSION_MINOR "6"
#define VORPALINE_VERSION_PATCH "12"
#define VORPALINE_VERSION "1.6.12"
#define VORPALINE_BUILD_NUMBER ""
#define VORPALINE_BUILD_DATE "Mon May 13 13:36:41 CEST 2019"
#define VORPALINE_SVN_REVISION "????"

#endif
