#ifndef GEOGRAM_BASIC_VERSION
#define GEOGRAM_BASIC_VERSION

#define VORPALINE_VERSION_MAJOR "1"
#define VORPALINE_VERSION_MINOR "7"
#define VORPALINE_VERSION_PATCH "1"
#define VORPALINE_VERSION "1.7.1"
#define VORPALINE_BUILD_NUMBER ""
#define VORPALINE_BUILD_DATE ""
#define VORPALINE_SVN_REVISION ""

#endif
