# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' 2D Semi-discrete Optimal Transport Map
#' 
#' @param X input data matrix.
#' @param epsilon maximum error for the optimization algorithm.
#' @param maxit maximum number of solver iterations.
#' @param verbose logical indicating wether to display optimization messages.
#' @return a list describing the resulting optimal transport map.
#' @keywords internal
dualGraphs2D <- function(X, epsilon, maxit, verbose) {
    .Call('_testOTM_dualGraphs2D', PACKAGE = 'testOTM', X, epsilon, maxit, verbose)
}

dualPotential2D <- function(Y, X, V, h, accuVerts) {
    .Call('_testOTM_dualPotential2D', PACKAGE = 'testOTM', Y, X, V, h, accuVerts)
}

#' Locate within a 2D RVD
#' 
#' Find the RVD cells where a set Q of query points is transported to.
#' @param Q input query matrix.
#' @param X input data used to build the RVD.
#' @param w weights of the RVD cells.
#' @return a vector of indices indicating where the query points are transported to.
#' @keywords internal
locateRVD2D <- function(Q, X, w) {
    .Call('_testOTM_locateRVD2D', PACKAGE = 'testOTM', Q, X, w)
}

locateRDT2D <- function(Q, V) {
    .Call('_testOTM_locateRDT2D', PACKAGE = 'testOTM', Q, V)
}

GoF2D <- function(X, Y, XY, U, epsilon, maxit, verbose) {
    .Call('_testOTM_GoF2D', PACKAGE = 'testOTM', X, Y, XY, U, epsilon, maxit, verbose)
}

