# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' 2D Semi-discrete Optimal Transport Map
#' 
#' @param X input data matrix.
#' @param epsilon maximum error for the optimization algorithm.
#' @param maxit maximum number of solver iterations.
#' @param verbose logical indicating wether to display optimization messages.
#' @return a list describing the resulting optimal transport map.
#' @keywords internal
dualGraphs2D <- function(X, epsilon, maxit, verbose) {
    .Call('_testOTM_dualGraphs2D', PACKAGE = 'testOTM', X, epsilon, maxit, verbose)
}

dualPotential2D <- function(Y, X, V, h, accuVerts) {
    .Call('_testOTM_dualPotential2D', PACKAGE = 'testOTM', Y, X, V, h, accuVerts)
}

#' Locate within a 2D RVD
#' 
#' Find the RVD cells where a set Q of query points is transported to.
#' @param Q input query matrix.
#' @param X input data used to build the RVD.
#' @param w weights of the RVD cells.
#' @return a vector of indices indicating where the query points are transported to.
#' @keywords internal
locateRVD2D <- function(Q, X, w) {
    .Call('_testOTM_locateRVD2D', PACKAGE = 'testOTM', Q, X, w)
}

#' Locate within a 2D RDT
#' 
#' Find the RDT triangles where a set Q of query points belongs to.
#' @param Q input query matrix.
#' @param V matrix of sorted triangle vertices.
#' @return a vector of indices indicating which triangles the query points belong.
#' @keywords internal
locateRDT2D <- function(Q, V) {
    .Call('_testOTM_locateRDT2D', PACKAGE = 'testOTM', Q, V)
}

#' 2D Goodness-of-fit Test Helper
#' 
#' Compute the quantiles of U with respect to X and Y, as well as the optimal transport map of the combined data.
#' @param X input data matrix.
#' @param Y input data matrix.
#' @param U sequence used to evaluate the integral.
#' @param center logical indicating if the centroids should be computed.
#' @param epsilon convergence threshold for optimization.
#' @param maxit max number of iterations before termination.
#' @param verbose logical indicating wether to display optimization messages.
#' @return a list, which contains the quantile indices, and the vertices of the combined optimal transport map.
#' @keywords internal
gof2D <- function(X, Y, U, center, epsilon, maxit, verbose) {
    .Call('_testOTM_gof2D', PACKAGE = 'testOTM', X, Y, U, center, epsilon, maxit, verbose)
}

#' 1D Test of Independece Helper
#' 
#' Compute the quantiles of U with respect to (X, Y).
#' @param XY input data matrix.
#' @param center logical indicating if the centroids should be computed.
#' @param epsilon convergence threshold for optimization.
#' @param maxit max number of iterations before termination.
#' @param verbose logical indicating wether to display optimization messages.
#' @return a matrix, represents either the centroid or the cells of the combined optimal transport map.
#' @keywords internal
dep1D <- function(XY, center, epsilon, maxit, verbose) {
    .Call('_testOTM_dep1D', PACKAGE = 'testOTM', XY, center, epsilon, maxit, verbose)
}

