# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dualGraphes2D <- function(X, epsilon, maxit, verbose) {
    .Call('_testOTM_dualGraphes2D', PACKAGE = 'testOTM', X, epsilon, maxit, verbose)
}

GoF2D <- function(X, Y, XY, U) {
    .Call('_testOTM_GoF2D', PACKAGE = 'testOTM', X, Y, XY, U)
}

